folder: ZG3.0
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG3.0/ZG3.0.zip
last_commit: aabff94993acf74a62595366e833de0eaf2da872
last_updated: '2026-02-10T06:36:23.517774+00:00'
version: 1.8
zip_file: ZG3.0.zip
