folder: ZG2.0
gcs_url: https://storage.googleapis.com/plode_resource/sdcard-assets/ZG2.0/ZG2.0.zip
last_commit: 74dabadfc011c8ff45a2410b87427a1ea3d23279
last_updated: '2025-11-19T18:39:59.348627+00:00'
version: 3.4
zip_file: ZG2.0.zip
